In [1]:
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)  # create a random value betwwen 0 to 1

tensor([[0.6511, 0.4845, 0.7543],
        [0.7513, 0.6332, 0.1749]])

In [8]:
# use of seed
torch.rand(2,3)

tensor([[0.7930, 0.3040, 0.5630],
        [0.6578, 0.8380, 0.7537]])

In [9]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[    136742711991696,           142770336,                   0],
        [                  0,                   0, 7310593858020254331]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [19]:
# find data type
x.dtype

torch.int64

In [20]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [22]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [23]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [24]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [26]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [27]:
c = torch.tensor([1, -2, 3, -4])

In [28]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [29]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [30]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [31]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [32]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [33]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [34]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.3000, 3.7000, 4.0000])

### 3. Reduction operation

In [35]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [36]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [37]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [38]:
# median
torch.median(e)

tensor(0.)

In [39]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [40]:
# product
torch.prod(e)

tensor(0.)

In [41]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [42]:
# variance
torch.var(e)

tensor(19.6000)

In [43]:
# argmax
torch.argmax(e)

tensor(5)

In [44]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [51]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [46]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [47]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [52]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [53]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 1., 5.],
        [5., 0., 4.],
        [3., 8., 8.]])

In [54]:
# determinant
torch.det(h)

tensor(-20.0000)

In [55]:
# inverse
torch.inverse(h)

tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

### 5. Comparison operations

In [56]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [57]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [58]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [59]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [60]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [61]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [62]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [63]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [64]:
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

## Inplace Operations

In [65]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])
tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])


In [66]:
m.add_(n)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [67]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [ ]:
n

tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])

In [68]:
torch.relu(m)

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [69]:
m.relu_()

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

In [70]:
m

tensor([[0.5098, 1.1259, 0.9638],
        [0.9448, 0.4670, 0.6286]])

## Copying a Tensor

In [71]:
a = torch.rand(2,3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [72]:
b = a

In [73]:
b

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [74]:
a[0][0] = 0

In [75]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [76]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [77]:
id(a)

136738364516080

In [78]:
id(b)

136738364516080

In [79]:
b = a.clone()

In [80]:
a

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [81]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [82]:
a[0][0] = 10

In [83]:
a

tensor([[10.0000,  0.2131,  0.3957],
        [ 0.6017,  0.4234,  0.5224]])

In [84]:
b

tensor([[0.0000, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [85]:
id(a)

136738364516080

In [86]:
id(b)

136738366199792

## Tensor Operations on GPU

In [87]:
torch.cuda.is_available()

True

In [88]:
device = torch.device('cuda')

In [89]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [90]:
# moving an existing tensor to gpu
b=a.to(device)

In [91]:
b+5

tensor([[15.0000,  5.2131,  5.3957],
        [ 5.6017,  5.4234,  5.5224]], device='cuda:0')

## Reshaping Tensors

In [92]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [94]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [95]:
b=torch.rand(2,3,4)
b

tensor([[[0.4175, 0.0340, 0.9157, 0.3079],
         [0.6269, 0.8277, 0.6594, 0.0887],
         [0.4890, 0.5887, 0.7340, 0.8497]],

        [[0.9112, 0.4847, 0.9436, 0.3904],
         [0.2499, 0.3206, 0.9753, 0.7582],
         [0.6688, 0.2651, 0.2336, 0.5057]]])

In [96]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [97]:
#unsqeeze
# image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [99]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0)

tensor([0.5889, 0.3118, 0.7235, 0.0591, 0.3780, 0.7077, 0.7936, 0.2313, 0.6106,
        0.0260, 0.9428, 0.8335, 0.6601, 0.2328, 0.9062, 0.9867, 0.5495, 0.1893,
        0.8159, 0.7631])

## NumPy and PyTorch

In [100]:
import numpy as np

In [101]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [102]:
b=a.numpy()

In [103]:
type(b)

numpy.ndarray

In [104]:
c=np.array([1,2,3])

In [105]:
c

array([1, 2, 3])

In [106]:
torch.from_numpy(c)

tensor([1, 2, 3])

In [107]:
torch.from_numpy(b)

tensor([1, 2, 3])